name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "✅ GitHub Actions workflow is working!"

      - name: Notify Slack (Success/Failure)
        if: always()   # Runs even if previous step fails
        run: |
          STATUS="✅ Passed"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="❌ Failed"
          fi
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"CI/CD Workflow Result: $STATUS\nRepo: $GITHUB_REPOSITORY\nCommit: $GITHUB_SHA\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
