name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - feature-branch
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run Tests
        run: |
          echo "Running tests..."
          pytest --maxfail=1 --disable-warnings -q

      # Step 5: Slack notification on success
      - name: Slack Notification (Success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "✅ CI/CD Passed for repo *${{ github.repository }}*, commit: ${{ github.sha }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # Step 6: Slack notification on failure with mention
      - name: Slack Notification (Failure)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "🚨 CI/CD *FAILED*! <@U09FB4F63A9> please check. Repo: *${{ github.repository }}*, commit: ${{ github.sha }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
